### ISSUE TITLE
Piece class in klasa#settings changed, it needs to be updated here

### ISSUE THREAD

**Issue by Kolkies** [dirigeants/klasa-dashboard-hooks#140]
### Describe the issue
In klasa#settings the Piece class is rewritten to work without the first client arg, this should be updated in the settings branch here too.

### Further details

- **discord.js version**: master
- **node.js version**: 10.15.3
- **Klasa version**: klasa#settings
- [ ] I have modified core files.
- [ ] I have tested the issue on latest master. Commit hash:

**Comment by kyranet** [comment]
Resolved in beb5344, core-pieces didn't need a modification since they use rest arguments, so only typings needed to change. Thanks you for reporting this!

**Comment by Kolkies** [comment]
https://donate.bot.sucks/h0mTqGxBioIDoU9IW4UyM2D2BI9rU1Oo.png

**Comment by kyranet** [comment]
Oh, I forgot about those, nice catch! Resolved in 8015f43

**Comment by Kolkies** [comment]
👍
